version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: benk-backend
    image: benk-backend:1.0.0
    env_file:
      - .env
    expose:
      - 8080

  # @Todo: Add Reverse Proxy - Caddy
