services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: benk-backend-app
    env_file:
      - .env
    expose:
      - 8080
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: benk-backend-gateway
    ports:
      - "8443:443"
    environment:
      - APP_HOST=app
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
