version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: benk-backend
    image: benk-backend:1.0.0
    env_file:
      - .env
    expose:
      - 8080

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    ports:
      - "8443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
