name: "CI Pipeline"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Format code
        run: go fmt ./... 
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Install make tool
        run: |
          sudo apt update -y
          sudo apt install -y make
      - name: Tidy mod file
        run: go mod tidy -v
      - name: Start audit
        run: make audit
  build:
    name: Build Docker Image
    if: github.event_name != 'pull_request'
    needs: [lint,audit]
    runs-on: ubuntu-latest
    env:
      CONTAINER_REGISTRY: docker.io
      DOCKER_IMAGE_NAME: arafetk/benktech-backend
      DOCKER_IMAGE_TAG: ${{ github.sha }}    
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}