name: "Golang"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# env:
#   REGISTRY: docker.io
#   IMAGE_NAME: "benktech-backend"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Format code
        run: go fmt ./...
