name: "Golang"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# env:
#   REGISTRY: docker.io
#   IMAGE_NAME: "benktech-backend"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
